---
version: "3.9"
services:
  maven:
    # based on maven:3.8-eclipse-temurin-11-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: webapps
        target: /webapps

  web:
    # based on adoptopenjdk/openjdk11:jre-11.0.6_10-alpine
    build:
      context: .
      dockerfile: Dockerfile.alpine
    volumes:
      - type: volume
        source: webapps
        target: /opt/tomcat/webapps/
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

volumes:
  webapps:
