---
version: "3.9"
services:
  git:
    image: alpine/git
    volumes:
      - ./:/git
    command: [
      "sh -c ",
      "rm -f done.lock && clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && touch done.lock",
    ]
